//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_Flightss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flightdb
    {
        public int FlightID { get; set; }
        public string Nameofflight { get; set; }
        public string Model { get; set; }
        public string Company { get; set; }
    }
}
