//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_Flightss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passangerdb
    {
        public int passengerID { get; set; }
        public string Nameofpassenger { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> CitiesID { get; set; }
        public Nullable<int> FlightID { get; set; } 

        public virtual Citiesdb Citiesdb { get; set; }

        public virtual Flightdb Flightdb { get; set; }  
    }
}
